export var special = {
    "PoisonersNeedle" : "This weapon is so small that, with a successful Dexterity (Sleight of Hand) check against a target's passive Perception, you may attack a target without them noticing.",
    "HookSword" : "When wielding two hook swords, you may treat them both as if they had the reach property. This property is counted when determining prerequisites for feats, abilities, and upgrades.",
    "RapierGauche" : "When wielding a rapier and gauche together with proficiency in the pairing, upgrades applied to either weapon can be used by either.",
    "ChainGauntlets" : "Your grapple range is increased by 5 feet when wearing chain gauntlets. Additionally, any target you are grappling is considered restrained.",
    "Lance" : "You have disadvantage when attacking a target within 5 feet of you with a lance. Additionally, a lance requires two hands to wield when not mounted.",
    "ImperialLance" : "You have disadvantage when attacking a target within 5 feet of you with an imperial lance. Additionally, an imperial lance requires two hands to wield when not mounted.",
    "Firestarter" : "This weapon attacks with a large flammable projectile that ignites upon impact. Any flammable objects not being worn or carried within 5 feet of the target are ignited whether the attack hits or misses. If the weapon misfires, this effect is applied to the wielder instead.",
    "Grenade" : "This weapon is thrown and explodes in a 10-foot radius. All creatures within the radius must make a Dexterity saving throw against the weapon's attack roll. On a failed save, a creature takes full damage. On a successful save, a creature takes half damage.",
    "GrenadeLauncher" : "This weapon fires grenades as ammunition. All special properties of the grenade are applied to the grenade launcher.",
    "Minigun" : "The minigun must be charged for one round before it can be fired. If the minigun fires no shots in a round or is unmounted, it must be charged again before it can be fired. Once charged, the minigun fires 1 + 1d6 bullets per attack. If the minigun misfires, rather than becoming unusable, the wielder takes damage as usual, and the weapon fires -1 bullets per misfire until repaired.", 
};